### ISSUE TITLE
Request: Add TypeScript support.

### ISSUE THREAD

**Issue by Chris2011** [vigetlabs/grunt-complexity#15]
I would like to test the complexity of my TypeScript files.
This would be great.

Regards

Chris

**Comment by kevde** [comment]
@Chris2011 try for the latest release. It now supports ES6. But I dont know if it also supports TS

**Comment by Chris2011** [comment]
@kevde thx I will try it. :)

**Comment by Chris2011** [comment]
Unfortunately, I don't use grunt anymore, so I will close this ticket, but if you say, that it should work with ES6 that would be great. Sry, but maybe someone else will find this ticket helpful or will test it :) Thx for the work anyway.
