### ISSUE TITLE
SAXParseException exception with pmd.xml out of jenkins.

### ISSUE THREAD

**Issue by theoneroof** [vigetlabs/grunt-complexity#38]
I just installed the grunt-complexity plugin into our project and have it generating the checkStyle and PMD reports.  We noticed though that the checkStyle report parses just fine while the pmd one throws a parser exception.  

Submitting a fix for it unless someone else wants to do it.

**Comment by jonbcampos** [comment]
ever make a fix for this?

**Comment by theoneroof** [comment]
Yeah I did. Its on my forked branch. I don't think this its being
maintained anymore

**Comment by jonbcampos** [comment]
trying now. thanks!

**Comment by nhunzaker** [comment]
Hey, I know I'm late to the game here, but I've folded in @theoneroof's change. Thank you for the fix!
