### ISSUE TITLE
method name <anonymous> breaks jenkins reporting

### ISSUE THREAD

**Issue by jonbcampos** [vigetlabs/grunt-complexity#43]
can we just remove the < >? or at least get the xml entities? Or maybe add a cdata around the method name? Just currently if blows up the pretty jenkins reports.

**Comment by jonbcampos** [comment]
fork from @theoneroof seems to handle it

npm install https://github.com/theoneroof/grunt-complexity --save-dev

**Comment by nhunzaker** [comment]
Cool. I plucked it over. I'll ship out a patch release shortly.

**Comment by nhunzaker** [comment]
Shipped. Checkout [`v0.3.1`](https://github.com/vigetlabs/grunt-complexity/releases/tag/v0.3.1)
